#!/usr/bin/env bash
# Configuring Nginx server so that /redirect_me is redirecting to another page
if ! command -v nginx &> /dev/null; then
	apt-get -y update
	apt-get -y install nginx
fi
ufw allow 80/tcp
mkdir -p /var/www/html/
echo "Hello World!" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
systemctl start nginx
