#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
echo "Ceci n'est pas une page" | tee /var/www/html/custom_404.html
echo "server {
    listen 80 default_server;
    server_name _;
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }
}" | tee /etc/nginx/sites-available/custom_404
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
service nginx reload
