#!/usr/bin/env bash
# This script accepts a string as an argument, displays "Usage: 5-is_the_host_on_the_netwirk {IP_ADDRESS}" if no argument passed and ping the IP 5 times
if [ "$#" -ne 1 ];
then
	echo "Usage: $0 {IP_ADDRESS}"
	exit 1
fi
IP_ADDRESS=$1
ping -c 5 "$IP_ADDRESS"
