#!/usr/bin/env bash
# This script shows all processes, for all users, including those which might not have a TTY, display in a user-oriented format, show process hierachy and displays a list of currently running processes
echo "PID PPID CMD"
ps axo pid,ppid,cmd --forest | sed 's/^/ /'
