#!/usr/bin/env bash
# This script cannot use "pgrep", the third line of the script must be "# shellcheck disable=SC2009" and displays lines containing the "bash" word, thus allowing one to easily get the PID of your Bash process
ps aux | grep bash
