#!/usr/bin/env bash
# This script in between each iteration of the loop, add a "sleep 2" and displays "To infinity and beyond" indefinitely
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
