#!/usr/bin/env bash
# This script that kills the process "7-highlander"
process_name="7-highlander"
if pgrep -f "$process_name" > /dev/null;
then
	echo "Killing $process_name"
	pkill -f "$process_name"
else
	echo "$process_name is not currently running"
fi
