#!/usr/bin/env bash
# This script uses "FizzBuzz" to display when the number is amultiple of 3 and 5, "Fizz" when the number is a multiple of, "Buzz" when the number is a multiple of 5, otherwise display the number and in a list format
for ((i = 1; i <= 100; i++));
do
	if ((i % 3 == 0)) && ((i % 5 == 0));
then
		echo "FizzBuzz"
	elif ((i % 3 == 0));
then 
		echo "Fizz"
	elif ((i % 5 == 0));
then
		echo "Buzz"
	else
		echo "$i"
	fi
done
