#!/usr/bin/env bash
# This script that displays the content of the file "/etc/passwd" and uses the while loop to display the username, user id and home directory path for the user
while read -r passwd
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
