#!/usr/bin/env bash
# This script uses the while loop to display the content of the file "/etc/passwd" using the while loop + IFS and "The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
while IFS=: read -r username x uid gid info home shell;
do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell"
	echo "User ID's place is protected by the passcode $info, more info about the user here: $uid $info"
	echo
done < "/etc/passwd"
