#!/usr/bin/env bash
# This script uses the while loop to display the content of the file "/etc/passwd" using the while loop + IFS and "The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
fname="/etc/passwd"
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	printf "The user %s is part of the %s gang, lives in %s and rides " "$f1" "$f4" "$f6"
	printf "%s. %s 's place is protected by the passcode %s, more info about the user here:" "$f7" "$f3" "$f2"
	printf " %s" "$f5"
	printf "\n"
done < "$fname"
