#!/usr/bin/env bash
# The script uses the awk to display the visitor IP along with the HTTP status code from Apache log file, not allowed to use "while", "for", "until", "cut, Download and commit the apache-access.log.file along with the answer files and "IP HTTP_CODE in a list format and see example
awk -F' ' '{ print $1 " " $9 }' apache-access.log
