#!/usr/bin/env bash
# This script uses the awk that groups visitors by IP and HTTP status code and displays this data, not allowed to use "while", "for", "until", "cut", Ordered from the greatest to the lowest number of occurences and see example, OCCURENCE_NUMBER IP HTTP_CODE and in list format
awK -F' ' '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -nr
