#!/usr/bin/env bash
# This script uses the while loop and the if, elif and else statements to display "bad luck" for the 4th lop iteration, "goodluck" for the 8th loop interation and "Best School" for the other interations
counter=1
while [ "$counter" -le 10 ];
do
	if [ "$counter" -eq 4 ];
then
	echo "bad luck"
	elif [ "$counter" -eq 8 ];
then
	echo "good luck"
else
	echo "Best School"
	fi
	((counter++))
done
