#!/usr/bin/env bash
# This script uses the while loop and case statement to display "4" and then "bad luck from China" for the 4th loop interation, "9" and then "bad luck from Japan" for the 9th loop iteration and "17" and then "bad luck from Italy" for the 17th loop iteration
counter=1
while [ "$counter" -le 20 ];
do
        echo "$counter"
        case $counter in
                "4")
                        echo "bad luck from China"
                        ;;
                "9")
                        echo "bad luck from Japan"
                        ;;
                "17")
                        echo "bad luck from Italy"
                        ;;
        esac
        ((counter++))
done
