#!/usr/bin/env bash
# This script uses the while loop and case statement to display "4" and then "bad luck from China" for the 4th loop interation, "9" and then "bad luck from Japan" for the 9th loop iteration and "17" and then "bad luck from Italy" for the 17th loop iteration
counter=1
while [ "$counter" -le 20 ];
do
	if [ "$counter" -eq 4 ];
then
	echo "bad luck from China"
	elif [ "$counter" -eq 9 ];
then
	echo "bad luck from Japan"
	elif [ "$counter" -eq 17 ];
then
	echo "bad luck from Italy"
	else
		echo "$counter"
	fi
	((counter++))
done
