#!/usr/bin/env bash
# This script uses the for loop and do not display hidden files to display the content of the current diretory, in a list form and where only the part of the name after the first dash is displayed
for file in *;
do
	if [ -f "$file" ];
then
		name_part=$(echo "$file" | cut -d'-' -f2-)
		echo "$name_part"
	fi
done
