#!/usr/bin/env bash
# This script gives information about the "school" file and uses the if and else, should check if the file exist and print if the file exists "school file exists and if the file does not exist "school file does not exist", If the file exists and print if the file is empty "school file is empty", if the file is not empty "school file is not empty", if the file is a regular file "school is a regular file and if the file is not a regualr file "(nothing)"
file="school"
if [ -e "$file" ];
then
	echo "school file exists"
	if [ -s "$file" ];
then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$file" ];
then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
