#!/usr/bin/env bash
# This script configures and Ubuntu server where "localhost" resolves to "127.0.0.2", "facebook.com" resolves to 8.8.8.8 and the checker is running on Docker, so make sure to read this
cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
