#!/usr/bin/env bash
# Must be 7 lines long or less and must be a new line at the end of the file
pkill apache2
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
